## Basics of NumPy
A fundamental package for numerical computing in Python.

#### 1. Importing NumPy

In [ ]:
# Import the NumPy library (usually as np).


import numpy as np

####  2. Creating Arrays

In [ ]:
# array() creates NumPy arrays.


a = np.array([1, 2, 3])           # 1D array
b = np.array([[1, 2], [3, 4]])    # 2D array

In [10]:
print(a)

[1 2 3]


In [11]:
print(b)

[[1 2]
 [3 4]]


#### 3. Special Arrays

In [ ]:
# Quick ways to create filled arrays.


# c = np.zeros((2, 3))              # Array of zeros
# d = np.ones((3, 3))               # Array of ones
e = np.eye(3,dtype=int,k=1)                     # Identity matrix



In [22]:
print(e)

[[0 1 0]
 [0 0 1]
 [0 0 0]]


####  4. Create Number Sequences

In [ ]:
# Ranges: arange() for steps, linspace() for evenly spaced numbers.


# f = np.arange(0, 10, 2)           # Even numbers from 0 to 8
g = np.linspace(0, 1, 5)          # 5 numbers from 0 to 1


In [28]:
print(g)

[0.   0.25 0.5  0.75 1.  ]


####  5. Array Shape & Info

In [ ]:
# Get shape, dimensions, and size of the array.


arr = np.array([[1, 2], [3, 4]])

# print(arr.shape)       # Shape of array
# print(arr.ndim)        # Number of dimensions
# print(arr.size)        # Total number of elements
print(arr.dtype)       # Data type of array elements


int64


####  6. Indexing and Slicing

In [ ]:
# Access rows, columns, or individual elements.


arr = np.array([[1, 2, 3], [4, 5, 6]])

# print(arr[0, 1])        # 2
# print(arr[:, 1])        # Second column
# print(arr[1, :])        # Second row


In [35]:
print(arr)

[[1 2 3]
 [4 5 6]]


#### 7. Reshape Arrays

In [ ]:
# Change the shape of the array.


a = np.arange(6)        # [0, 1, 2, 3, 4, 5]
b = a.reshape((2, 3))   # [[0, 1, 2], [3, 4, 5]]


In [44]:
a = np.arange(7)        # [0, 1, 2, 3, 4, 5]

In [45]:
b = a.reshape((2, 3))   # [[0, 1, 2], [3, 4, 5]]

ValueError: cannot reshape array of size 7 into shape (2,3)

In [43]:
print(b)

[[0 1 2]
 [3 4 5]]


#### 6. Mathematical Operations

In [46]:


# Perform math element-wise or use built-in functions like mean().

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# print(x + y)         # Element-wise addition
# print(x * y)         # Element-wise multiplication

# print(np.mean(x))    # Mean
# print(np.sum(x))     # Sum
# print(np.max(x))     # Max value


In [51]:
print("X: ",x,"\n","Y: ",y)

X:  [1 2 3] 
 Y:  [4 5 6]


In [68]:
np.mean(np.concatenate((x,y)))

np.float64(3.5)

####  9. Filter with Conditions

In [ ]:
# Get only the values that match a condition.


arr = np.array([1, 2, 3, 4, 5])
print(arr[arr > 3])     # [4, 5]


[4 5]


In [ ]:
np.array([1, 2, 3, 4, 5])>3

####  10. Random Numbers

In [ ]:
# Generate random arrays.



np.random.rand(2, 2)        # Random floats [0, 1)
np.random.randint(0, 10, 5) # Random ints between 0–9

#### 11. Saving and Loading Arrays

In [ ]:
# Store arrays for later use.



arr = np.array([1, 2, 3])
np.save('my_array.npy', arr)
loaded = np.load('my_array.npy')
print(loaded)


### Project: Student Grades Analyzer

**Objective:**

- Create a NumPy-based program that:

- Stores students' scores.

- Calculates average, highest, and lowest scores.

- Finds students who passed or failed.

**Scenario:**

You have the scores of 5 students in 3 subjects: `Math`, `Science`, and `English`. You want to analyze their performance.

-  1. Create the Data
    - `np.array([1, 2, 3])` 
-  2. Basic Info
    - `scores.shape`
-  3. Average Score per Student
    - `np.mean(scores, axis=1)`
-  4. Average Score per Subject
    - `np.mean(scores, axis=0)`
-  5. Find the Highest & Lowest Scores
    - `np.max(scores)`
-  6. Determine Pass/Fail (a student passes if their average is 60 or more.)
    - `np.where(passed)[0]`

In [ ]:
# 1. Create the Data

import numpy as np

# Each row = a student, each column = a subject
scores = np.array([
    [85, 78, 90],
    [66, 70, 60],
    [95, 88, 92],
    [45, 50, 52],
    [75, 80, 85]
])


In [ ]:
# 2. Basic Info

print("Shape of scores:", scores.shape)
print("Total students:", scores.shape[0])
print("Subjects:", scores.shape[1])


In [ ]:
# 3. Average Score per Student

student_avg = np.mean(scores, axis=1)
print("Average scores per student:", student_avg)


In [ ]:
# 4. Average Score per Subject

subject_avg = np.mean(scores, axis=0)
print("Average scores per subject (Math, Science, English):", subject_avg)


In [ ]:
# 5. Find the Highest & Lowest Scores

print("Highest score overall:", np.max(scores))
print("Lowest score overall:", np.min(scores))


In [ ]:
# 6. Determine Pass/Fail
# Assume a student passes if their average is 60 or more.

passed = student_avg >= 60
print("Passed students:", np.where(passed)[0])  # Show indices
print("Failed students:", np.where(~passed)[0])


In [ ]:
# Optional Challenge Ideas

# Add student names and match them with results.

# Add a feature to input new student scores.

# Find top-performing student(s).